---
- hosts: localhost
  gather_facts: no
  tasks:
    # This is just to dynamically add the host to the inventory
    - name: Adding system to the Ansible Inventory.  
      add_host:
        name: "{{ satellite_hostname }}"
      
- hosts: "{{ hostvars['localhost']['satellite_hostname'] }}"
  tasks:
    - name: Installing satellite
      tags: satellite-installer
      include_role:
        name: satellite-installer
      