---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Deploy VM
      tags: deploy-vm  
      include_role:
        name: rhevdeploy
      
- hosts: "{{ hostvars['localhost']['hostname'].msg }}"
  tasks:
    - name: configure VM for installing satellite 
      tags: configure-vm
      include_role:
        name: configurevm

    - name: Installing satellite
      tags: satellite-installer
      include_role:
        name: satellite-installer
      