---

- name: Change Hostname
  hostname:
    name: "{{ satellite_hostname }}"

- name: disable the firewalld 
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Add Entry in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ satellite_ip }}"
    line: "{{ satellite_ip }} {{ satellite_hostname }}"
    owner: root
    group: root
    mode: 0644

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  when: version_type == "Offical"

- name: Installing Satellite "{{ satellite_version }}" packages
  yum:
    name: satellite
    state: latest

- pause:
    seconds: 30

- name: Running the satellite-installer for 6.2
  command: satellite-installer --scenario satellite --foreman-initial-organization "RedHat" --foreman-initial-location "Pune" --foreman-admin-username admin --foreman-admin-password redhat --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false
  when: satellite_version == "6.2"

- name: Running the satellite-installer for 6.3/6.4
  command: satellite-installer --scenario satellite --foreman-initial-organization "RedHat" --foreman-initial-location "Pune" --foreman-admin-username admin --foreman-admin-password redhat --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false --disable-system-checks
  when: satellite_version == "6.3" or satellite_version == "6.4" or satellite_version == "6.5"