---
- name: Installing Satellite "{{ satellite-version }}" packages
  yum:
    name: satellite
    state: latest

- pause:
    seconds: 30

- name: Running the satellite-installer
  command: satellite-installer --scenario satellite --foreman-initial-organization "RedHat" --foreman-initial-location "Pune" --foreman-admin-username admin --foreman-admin-password redhat --foreman-proxy-dns-managed=false --foreman-proxy-dhcp-managed=false