---
# tasks file for satellite-installer
- import_tasks: subscription-manager.yml
  when: version_type == "Current-release"
  tags: subscription-manager

- import_tasks: ohsnap-release.yml
  when: version_type == "Latest-snap"

- import_tasks: install.yml