- block:
  - name: Get Free host On RHEV
    uri:
      url: "{{ rhevurl }}/hosts/{{item}}"
      method: GET
      user: "{{ rhevusername }}"
      password: "{{ rhevpassword }}"
      return_content: yes
      headers:
        Version: 4
        Accept: "application/xml"
        Content-type: "application/xml"
    ignore_errors: yes
    register: cmd_stat
    tags: gethost

  - name: Retriving size.
    xml:
      xmlstring: "{{ cmd_stat.content }}"
      xpath: /host/statistics/statistic/values/value/datum
      content: text
    register: availablesize
    tags: gethost


  - name: storage_domain size
    debug:
      var: availablesize.matches[2].datum
    tags: gethost

  - set_fact: var2={{item}}
    when: availablesize.matches[2].datum | int > 15309411
    tags: gethost

  when: var2 is not defined

