- block:
  - name: Get Free Storage Domain On RHEV
    uri:
      url: "{{ rhevurl }}/storagedomains/{{item}}"
      method: GET
      user: "{{ rhevusername }}"
      password: "{{ rhevpassword }}"
      return_content: yes
      headers:
        Version: 4
        Accept: "application/xml"
        Content-type: "application/xml"
    ignore_errors: yes
    register: cmd_stat
    tags: storagedomain

  - name: Retriving size.
    xml:
      xmlstring: "{{ cmd_stat.content }}"
      xpath: /storage_domain/available
      content: text
    register: availablesize
    tags: storagedomain

  - name: storage_domain size
    debug:
      var: availablesize.matches[0].available
    tags: storagedomain

  - set_fact: var1={{item}}
    when: availablesize.matches[0].available | int > 153094113280
    tags: storagedomain

  when: var1 is not defined

